# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: totp.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntotp.proto\x12\x0cgrpc_service\"&\n\nToTPObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"<\n\x0e\x41\x64\x64ToTPRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0c\n\x04totp\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"!\n\x0f\x41\x64\x64ToTPResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"$\n\x12\x46indAllToTPRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\"A\n\x13\x46indAllToTPResponse\x12*\n\x08response\x18\x02 \x03(\x0b\x32\x18.grpc_service.ToTPObject\"1\n\x11RemoveToTPRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0c\n\x04totp\x18\x02 \x01(\t\"$\n\x12RemoveToTPResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xfa\x01\n\x05ToTPs\x12H\n\x07\x41\x64\x64ToTP\x12\x1c.grpc_service.AddToTPRequest\x1a\x1d.grpc_service.AddToTPResponse\"\x00\x12T\n\x0b\x46indAllToTP\x12 .grpc_service.FindAllToTPRequest\x1a!.grpc_service.FindAllToTPResponse\"\x00\x12Q\n\nRemoveToTP\x12\x1f.grpc_service.RemoveToTPRequest\x1a .grpc_service.RemoveToTPResponse\"\x00\x42\x45ZCgithub.com/sudora1n/google-auth-bot/internal/microservice-api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'totp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/sudora1n/google-auth-bot/internal/microservice-api/proto'
  _globals['_TOTPOBJECT']._serialized_start=28
  _globals['_TOTPOBJECT']._serialized_end=66
  _globals['_ADDTOTPREQUEST']._serialized_start=68
  _globals['_ADDTOTPREQUEST']._serialized_end=128
  _globals['_ADDTOTPRESPONSE']._serialized_start=130
  _globals['_ADDTOTPRESPONSE']._serialized_end=163
  _globals['_FINDALLTOTPREQUEST']._serialized_start=165
  _globals['_FINDALLTOTPREQUEST']._serialized_end=201
  _globals['_FINDALLTOTPRESPONSE']._serialized_start=203
  _globals['_FINDALLTOTPRESPONSE']._serialized_end=268
  _globals['_REMOVETOTPREQUEST']._serialized_start=270
  _globals['_REMOVETOTPREQUEST']._serialized_end=319
  _globals['_REMOVETOTPRESPONSE']._serialized_start=321
  _globals['_REMOVETOTPRESPONSE']._serialized_end=357
  _globals['_TOTPS']._serialized_start=360
  _globals['_TOTPS']._serialized_end=610
# @@protoc_insertion_point(module_scope)
