# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_pb2 as user__pb2


class UsersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrReturnUser = channel.unary_unary(
                '/grpc_service.Users/CreateOrReturnUser',
                request_serializer=user__pb2.CreateOrReturnUserRequest.SerializeToString,
                response_deserializer=user__pb2.CreateOrReturnUserResponse.FromString,
                )
        self.ChangeLang = channel.unary_unary(
                '/grpc_service.Users/ChangeLang',
                request_serializer=user__pb2.ChangeLangRequest.SerializeToString,
                response_deserializer=user__pb2.ChangeLangResponse.FromString,
                )


class UsersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrReturnUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeLang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrReturnUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrReturnUser,
                    request_deserializer=user__pb2.CreateOrReturnUserRequest.FromString,
                    response_serializer=user__pb2.CreateOrReturnUserResponse.SerializeToString,
            ),
            'ChangeLang': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeLang,
                    request_deserializer=user__pb2.ChangeLangRequest.FromString,
                    response_serializer=user__pb2.ChangeLangResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.Users', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Users(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrReturnUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.Users/CreateOrReturnUser',
            user__pb2.CreateOrReturnUserRequest.SerializeToString,
            user__pb2.CreateOrReturnUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeLang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.Users/ChangeLang',
            user__pb2.ChangeLangRequest.SerializeToString,
            user__pb2.ChangeLangResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
