# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cgrpc_service\"*\n\nUserObject\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0c\n\x04lang\x18\x02 \x01(\t\"+\n\x19\x43reateOrReturnUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\"H\n\x1a\x43reateOrReturnUserResponse\x12*\n\x08response\x18\x01 \x01(\x0b\x32\x18.grpc_service.UserObject\"1\n\x11\x43hangeLangRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0c\n\x04lang\x18\x02 \x01(\t\"$\n\x12\x43hangeLangResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xc5\x01\n\x05Users\x12i\n\x12\x43reateOrReturnUser\x12\'.grpc_service.CreateOrReturnUserRequest\x1a(.grpc_service.CreateOrReturnUserResponse\"\x00\x12Q\n\nChangeLang\x12\x1f.grpc_service.ChangeLangRequest\x1a .grpc_service.ChangeLangResponse\"\x00\x42\x45ZCgithub.com/sudora1n/google-auth-bot/internal/microservice-api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/sudora1n/google-auth-bot/internal/microservice-api/proto'
  _globals['_USEROBJECT']._serialized_start=28
  _globals['_USEROBJECT']._serialized_end=70
  _globals['_CREATEORRETURNUSERREQUEST']._serialized_start=72
  _globals['_CREATEORRETURNUSERREQUEST']._serialized_end=115
  _globals['_CREATEORRETURNUSERRESPONSE']._serialized_start=117
  _globals['_CREATEORRETURNUSERRESPONSE']._serialized_end=189
  _globals['_CHANGELANGREQUEST']._serialized_start=191
  _globals['_CHANGELANGREQUEST']._serialized_end=240
  _globals['_CHANGELANGRESPONSE']._serialized_start=242
  _globals['_CHANGELANGRESPONSE']._serialized_end=278
  _globals['_USERS']._serialized_start=281
  _globals['_USERS']._serialized_end=478
# @@protoc_insertion_point(module_scope)
