version: "3.8"

services:
  app:
    build: 
      context: ..
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    pull_policy: never
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres

    volumes:
      - ../config/api.env:/app/config/api.env

    ports:
      - "50051:50051"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_DB" ]
      interval: 1s
      timeout: 1s
      retries: 10
